### ISSUE TITLE
Agregar alumnos como colaboradores

### ISSUE THREAD

**Issue by mentorrolling** [mentorrolling/javascript-22i#1]
Pedir a los alumnos sus usuarios de github para agregarlos como colaboradores.

**Comment by mentorrolling** [comment]
Gracias @JuanAgusAlej por cerrar el issue

**Comment by aisoldati** [comment]
Hola @mentorrolling

**Comment by Dharez1** [comment]
Muy bonito tu repo cacho @pmarino2013

**Comment by JuanAgusAlej** [comment]
hola @mentorrolling

**Comment by RoberOusset** [comment]
hola @mentorrolling !

**Comment by danlantuc** [comment]
hola @mentorrolling

**Comment by Eliezerep98** [comment]
Hi there!
