### ISSUE TITLE
Tarea para el 13/12/21

### ISSUE THREAD

**Issue by mentorrolling** [mentorrolling/javascript-22i#3]
**Tarea**

- Escribe una clase Producto para crear objetos.
- Estos objetos, deben presentar las propiedades código, nombre y precio, además del método imprime datos, el cual escribe por pantalla los valores de sus propiedades.
- Posteriormente, cree tres instancias de este objeto y guárdalas en un array.
- Por último, utilice el método imprime datos para mostrar por pantalla los valores de los tres objetos instanciados.

**Comment by JuanAgusAlej** [comment]
Fue realizada la tarea y subida @mentorrolling

**Comment by mentorrolling** [comment]
Muy bien @JuanAgusAlej

**Comment by JuanAgusAlej** [comment]
Se agrego la seguridad a la extraccion de saldo

**Comment by Dharez1** [comment]
Tarea 13 de Dic terminada y subida

**Comment by mentorrolling** [comment]
@MauroRomo1 Excelente la tarea. Felicitaciones

**Comment by JuanAgusAlej** [comment]
Se modifico la condicion de la retirada de saldo

**Comment by Eliezerep98** [comment]
Tarea POO del 13/12 Realizada y subida @mentorrolling
